### ISSUE TITLE
Missing /app/entrypoint-last.sh

### ISSUE THREAD

**Issue by sbkg0002** [SeniorHeld/f1tv-rtmp#1]
Hi!

First of all: thanks for sharing! Really appreciating!

As for the HLS streaming, is the `/app/entrypoint-last.sh` committed somewhere?
https://github.com/SeniorHeld/f1tv-rtmp/blob/main/Dockerfile-hls#L21

Thanks!

**Comment by hTobi02** [comment]
Hello!

Thanks for using my script. 

I may have fixed it. You should be able to use `/app/entrypoint.sh`, but you need the new Dockerfile I just commited. 
Inside Docker, hls uses port 80 and for browser viewing you can use [http://localhost/player.html](http://localhost/player.html) or vlc [http://localhost/hls/f1tv.m3u8](http://localhost/hls/f1tv.m3u8).
If you need a more complex setup, please edit "player.html" according to your needs and rebuild the image. 

If you find another issue, please let me know.

**Comment by sbkg0002** [comment]
Thanks for the quick response!

Do you mean the latest `Docker-hls` file, or just the plain `Dockerfile`? 
Building the default one, only exposes rtmp:
```root@1342bbd3cdbf:/record# netstat -na| grep LISTEN
tcp        0      0 0.0.0.0:1935            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN
tcp6       0      0 :::1935                 :::*                    LISTEN
```

**Comment by hTobi02** [comment]
I meant the latest `Dockerfile-hls`. 
https://github.com/SeniorHeld/f1tv-rtmp/blob/main/Dockerfile-hls

**Comment by sbkg0002** [comment]
Thanks. Apparently HLS is on http://localhost/f1tv.m3u8!

**Comment by hTobi02** [comment]
My fault, that's what I meant. 
Thanks for the info!

**Comment by sbkg0002** [comment]
Question: How do you limit the IPs that can access the container? Simple `allow` and `deny` blocks in `http.server.location=/` results in:
```
f1tv-rtmp  | [tcp @ 0x560c4f4d70c0] Connection to tcp://127.0.0.1:1935 failed: Connection refused
f1tv-rtmp  | [rtmp @ 0x560c4f4a4b00] Cannot open connection tcp://127.0.0.1:1935
f1tv-rtmp  | rtmp://127.0.0.1:1935/live/f1tv: Connection refused
```

Sorry, nginx newbie here.

**Comment by hTobi02** [comment]
Actually this isn't limited. Are you using [nginx_hls.conf](https://github.com/SeniorHeld/f1tv-rtmp/blob/main/nginx_hls.conf)?
You should be able to use the `allow` and `deny` blocks inside the `server` block and not inside `http.server.location`
It's really good described [here](https://docs.nginx.com/nginx/admin-guide/security-controls/controlling-access-proxied-tcp/)

**Comment by sbkg0002** [comment]
> Actually this isn't limited. Are you using [nginx_hls.conf](https://github.com/SeniorHeld/f1tv-rtmp/blob/main/nginx_hls.conf)? You should be able to use the `allow` and `deny` blocks inside the `server` block and not inside `http.server.location` It's really good described [here](https://docs.nginx.com/nginx/admin-guide/security-controls/controlling-access-proxied-tcp/)

I am, thanks.
Aparently the issue is that every connection is logged as my routers IP.

**Comment by hTobi02** [comment]
Which OS do you use?
Under Linux and MacOS it should work without problems. 
Under Windows I get my virtual NIC address. 

What physical setup are you using?
Are you trying to access it via the Internet?
Maybe your router will work as a reverse proxy then?
